# -*- coding: utf-8 -*-
"""sentiment analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AD3mraG7uNkwhTcgjqHbWyfqzMNfg3L3
"""

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download the VADER lexicon if not already downloaded
nltk.download('vader_lexicon')

def sentiment_analysis(text):
    # Initialize the SentimentIntensityAnalyzer
    sia = SentimentIntensityAnalyzer()

    # Analyze the sentiment of the text
    sentiment = sia.polarity_scores(text)

    # Determine the sentiment based on the compound score
    if sentiment['compound'] >= 0.05:
        return "Positive"
    elif sentiment['compound'] <= -0.05:
        return "Negative"
    else:
        return "Neutral"

# Example usage
text = "I loved the new product, it's amazing!"
print(sentiment_analysis(text))  # Output: Positive

text = "The product was okay, nothing special."
print(sentiment_analysis(text))  # Output: Neutral

text = "I hated the product, it's terrible!"
print(sentiment_analysis(text))  # Output: Negative